[package]
name = "aoc_util"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc_util"
path = "src/lib.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.15.*"
